FROM java:8-jdk-alpine

VOLUME /tmp

COPY ./target/netflix-eureka-naming-server-0.0.1-SNAPSHOT.jar /users/ntahar2/workspace/

WORKDIR /users/ntahar2/workspace

RUN sh -c 'touch netflix-eureka-naming-server-0.0.1-SNAPSHOT.jar'

ENTRYPOINT ["java","-jar","netflix-eureka-naming-server-0.0.1-SNAPSHOT.jar"]
