FROM java:8-jdk-alpine

VOLUME /tmp

COPY ./target/currency-api-0.0.1-SNAPSHOT.jar /users/ntahar2/workspace/

WORKDIR /users/ntahar2/workspace

RUN sh -c 'touch currency-api-0.0.1-SNAPSHOT.jar'

ENTRYPOINT ["java","-jar","currency-api-0.0.1-SNAPSHOT.jar"]
